name: Dont gute nacht today

on:
  workflow_dispatch:

jobs:
  nope:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Dont gute nacht today
        run: ./dont_run_today.sh

      - name: Commit dont run today
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git diff --quiet && git diff --staged --quiet || (git commit -am "chore: dont run gute nacht today :ok_hand:" && git push)
