name: Gute nacht today

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  yes_pls:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Gute nacht today
        run: ./run_today.sh

      - name: Commit run today
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git diff --quiet && git diff --staged --quiet || (git commit -am "chore: dont run gute nacht today :ok_hand:" && git push)
